namespace XafHeadless.Api.Tests;

// Regenerated by the Task 1 (26.1 / OutlookInspired) model spike and finalized in Task 2 against the
// live host's real projection output (GET /api/model/views/{viewId}, authenticated as
// Admin@company1.com) -- discovered, not guessed.
//
// CHOSEN TARGET PAIR (primary, for list/detail rendering, OData reads, command, save round-trip):
//   Order_ListView / Order_DetailView -- lookups (Customer, Store, Employee) + an aggregated nested
//   collection (OrderItems). Guid key (BaseObject.ID); default property InvoiceNumber; 55,000 rows.
//
// VALIDATION-RICH TYPE (Task 2's save/validation 422 test target): Employee. Order carries NO
// [RuleRequiredField]; Employee carries real ones (FirstName/LastName/Title/Email/Address/City),
// confirmed live: Employee_DetailView now reports Required=true on FirstName (closes the old
// metadata/save Required-mismatch finding from the original POC).
public static class KnownModel {
    public const int ViewsCountAtSpike = 492;

    // Demo logon (public demo fixtures; the operative values live in testsettings.json). The password
    // is blank -- the demo seeds Admin@{tenant} with no password. TenantByEmailResolver maps the email
    // domain to the tenant DB (Admin@company1.com -> OutlookInspiredDemo_company1).
    public const string AdminUserName = "Admin@company1.com";
    public const string AdminPassword = "";

    // ---- Primary pair: Order ----
    public const string OrderListViewId = "Order_ListView";
    public const string OrderDetailViewId = "Order_DetailView";
    public const string OrderKeyMember = "ID";                 // OData EntityType key (Guid); confirmed live via ViewMetadata.KeyMember
    public const string OrderCollectionMember = "OrderItems";  // aggregated nested collection on Order_DetailView
    public const string OrderCollectionViewId = "Order_OrderItems_ListView"; // live nestedList.ViewId
    public const string OrderCollectionMasterKeyMember = "Order";           // live nestedList.MasterKeyMember (OrderItem.Order)
    // Representative Order_ListView columns, verbatim from the live projection.
    public const string OrderColumn1 = "InvoiceNumber";
    public const string OrderColumn2 = "OrderDate";
    public const string OrderColumn3 = "TotalAmount";

    // ---- Two-role trimming fixture (Task 2: no seeded demo role denies a single Order member --
    // see TestFixturesController for provenance) ----
    public const string RestrictedDeniedMember = OrderColumn3; // "TotalAmount": real ListView column + DetailView item, non-key, non-collection

    // ---- PH2-002: same restricted role, additive member-level WRITE deny (read is untouched) ----
    public const string RestrictedWriteDeniedMember = "PONumber"; // == OrderScalarMember below; kept as its own named constant to mirror RestrictedDeniedMember's naming

    // ---- Validation-rich type: Employee ----
    public const string EmployeeListViewId = "Employee_ListView";
    public const string EmployeeDetailViewId = "Employee_DetailView";
    public const string EmployeeKeyMember = "ID";
    public const string EmployeeCollectionMember = "Evaluations";
    public const string EmployeeRequiredMember = "FirstName";  // carries [RuleRequiredField]; confirmed live Required=true

    // ---- GAP-010: link/unlink. AssignedEmployeeTasks is a NON-aggregated many-to-many with EmployeeTask
    // (Employee.AssignedEmployeeTasks <-> EmployeeTask.AssignedEmployees) -- the link/unlink target. AssignedTasks
    // is [Aggregated] (owned) -> link/unlink must be rejected. Evaluations (above) is also aggregated: the
    // projected LayoutNode.Aggregated flag must be true for it. ----
    public const string EmployeeSharedCollectionMember = "AssignedEmployeeTasks"; // non-aggregated m2m -> link/unlink OK
    public const string EmployeeAggregatedCollectionMember = "AssignedTasks";     // [Aggregated] -> link/unlink rejected (400)

    // ---- GAP-001: reference/enum member writes on Order ----
    public const string OrderReferenceMember = "Customer";     // Order.Customer -- reference (lookup) member, Guid FK
    public const string OrderReferenceMemberKeyMember = "ID";  // Customer's own key member (also "ID")
    public const string OrderEnumMember = "ShipmentStatus";    // Order.ShipmentStatus -- [JsonConverter(JsonStringEnumConverter)]
    public const string OrderEnumValueAwaiting = "Awaiting";
    public const string OrderEnumValueTransit = "Transit";

    // ---- Fix pass regression guard: an ordinary scalar (non-reference, non-enum) member on Order ----
    public const string OrderScalarMember = "PONumber"; // plain string member

    // ---- GAP-003: create flow ----
    public const string EmployeeRequiredMemberLastName = "LastName"; // second [RuleRequiredField] member, left unset to prove 422 names an omitted required member

    // ---- GAP-009: N-view sweep -- Customer, Product. Both already OData-exposed in Startup.cs
    // (options.BusinessObject<Customer/Product>()); ids/KeyMembers confirmed live via
    // GET /api/model/views/{id} against the running host, not guessed -- both follow the
    // {Type}_ListView/{Type}_DetailView convention Order/Employee already use. ----
    public const string CustomerListViewId = "Customer_ListView";
    public const string CustomerDetailViewId = "Customer_DetailView";
    public const string CustomerKeyMember = "ID";

    public const string ProductListViewId = "Product_ListView";
    public const string ProductDetailViewId = "Product_DetailView";
    public const string ProductKeyMember = "ID";

    // ---- GAP-004: navigation menu projection ----
    // Live GET api/model/navigation (Admin@company1.com) returned, in this exact model-driven order:
    //   Employee, Evaluation, Customer, Order, Product -- i.e. Employee_ListView is FIRST, not Order.
    // Discovered live, not guessed: the demo's nav tree groups Employee/Evaluation (HR-ish) before
    // Sales (Customer/Order/Product); GAP-004's flatten-and-filter projection preserves that order.
    public const string NavigationFirstItemViewId = EmployeeListViewId;
    public const string EvaluationListViewId = "Evaluation_ListView"; // legitimately included (OData-exposed + ListView + CanRead) -- not in the brief's explicit assert list, but not excluded either
    // Must be excluded even though it has a real ListView + EDM schema presence: ApplicationUser is
    // NOT in WebApiOptions.BusinessObjects (Startup.cs never calls options.BusinessObject<ApplicationUser>()),
    // so GET api/odata/ApplicationUser 404s live -- confirmed before writing NavigationProjector's rule 2.
    public const string ApplicationUserListViewId = "ApplicationUser_ListView";

    // BUG-001 (fixed 2026-07-13): Customer.Logo / Product.Image / Employee.Picture.Data are raw byte[]
    // scalars. The demo's DevExpress model reports IsList==true for them, so the projector USED TO emit a
    // nested "list of Byte" node (Kind="nestedList", ViewId "Byte_ListView") that 404s from
    // GET /api/model/views/Byte_ListView -- surfacing live as an inline "Failed to load view metadata" error
    // in that nested section (the owner hit it running the POC; first noted as a GAP-009 quirk).
    // ViewMetadataProjector now classifies a non-business-object IsList member as an "image" item (byte[])
    // rather than a nested collection -- see IsBusinessObjectCollection. This id must NEVER appear as a
    // nestedList ViewId again (regression guard below).
    public const string ByteListViewId = "Byte_ListView";  // BUG-001: must never be a nestedList ViewId
    public const string CustomerImageMember = "Logo";      // Customer.Logo: byte[] -> "image" item (BUG-001)

    // BUG-002: Customer_DetailView carries both a nested collection over a NON-exposed child type and one over
    // an exposed child type -- the projector must omit the former (its data fetch would 404) and keep the latter.
    public const string CustomerOmittedNestedMember = "Employees"; // -> ObservableCollection<CustomerEmployee>; CustomerEmployee is a join type never passed to options.BusinessObject<T>() -> tab omitted
    public const string CustomerKeptNestedMember = "Orders";       // -> Order, OData-exposed -> tab kept

    // ---- DATA-001: lookup-classification predicate reconciliation ----
    // Host-owned LookupProbe (Development-only fixture, dev-gated in Startup.WithSharedBusinessObjects)
    // with a one-way, inverse-less reference `Ref` to the persistent shared TaxRate -- the "Direction A"
    // case (IsAssociation false / IsPersistent true) the OLD divergent predicates classified
    // inconsistently (ClassifyDataType -> "string" while ProjectLookup populated Lookup). View id follows
    // the auto-generated {Type}_DetailView convention already used by every other pair; confirmed live
    // against the running host (GET /api/model/views/LookupProbe_DetailView returns 200 with a Ref item).
    public const string LookupProbeDetailViewId = "LookupProbe_DetailView";
    public const string LookupProbeReferenceMember = "Ref";

    // ---- GAP-002: conditional-appearance projection ----
    // Employee.Evaluations nested tab renders Employee_Evaluations_ListView (verified live: the
    // Employee_DetailView layout's Evaluations nestedList.ViewId). Evaluation carries an [Appearance]
    // rule Rating='Good' with FontColor="Green", TargetItems="*", Context="Employee_Evaluations_ListView";
    // System.Drawing.Color.Green normalizes to CSS hex #008000. Sibling rules bound to the
    // "Employee_Evaluations_ListView_Child" clone context must NOT appear on this view (e.g. the Blue
    // StartOn rule) -- proves Context honoring. Verified live via GET api/model/views before writing.
    public const string EvaluationNestedListViewId = "Employee_Evaluations_ListView";
    public const string EvaluationAppearanceCriteria = "Rating='Good'";
    public const string EvaluationAppearanceFontColor = "#008000";
    public const string EvaluationChildOnlyFontColor = "#0000FF"; // Blue -- _Child-context only, must be absent here
    // GAP-002 enum-fix: Rating is the appearance rule's referenced enum member, but it is NOT a column of
    // Employee_Evaluations_ListView (verified live: absent from that view's projected Columns) -- the case
    // AppearanceEnums exists to cover.
    public const string EvaluationRatingMember = "Rating";
    // A live demo lookup that is ACTUALLY present as an item in Order_DetailView (verified live: the demo's
    // custom Order_DetailView layout contains Employee as its only reference editor — Customer/Store are NOT
    // laid out on it). Bidirectional association (IsAssociation true, inverse "Orders").
    public const string OrderEmployeeLookupMember = "Employee";
}
